# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112edd52dec197908a3f25890baa110372cc049bf3d481c087a82eb9e9fd4ea97224aa0600b32d4c3ac2401f4034b6aeb7c63461675f1caca0b7092465ba466f

test:
  secret_key_base: a381c21ee76222c4ffbfe7d3a53049e5a88b6b1ee11d603b6e76781b74338cf68aa24a08e7bb95613e3f846ad307c6cd8cab262fb7ec96130dc03ef80304bc1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
